### ISSUE TITLE
I belive there is something wrong with the model

### ISSUE THREAD

**Issue by jafioti** [theblackcat102/edgedict#3]
I have my own RNN-T project and I heavily borrowed from your model. I also can only reach around 60% WER, and when inspecting the outputs the model seems to be outputting way to many blank tokens. I can't even get it to fit to a few examples, because while the loss goes to nearly 0, the transcriptions outputted are mostly blanks, which causes the transcription to get cut off and results in a garbage WER. I am currently looking into what is wrong, perhaps something with the greedy_decode function. Please let me know if you have found anything.

**Comment by muramasa2** [comment]
I also have my own RNN-T project and verified it.
I could reached 22% WER with it, so maybe the code on the repository doesn't have any problem.
So I guess you should review the hyper param and your train data, and fix it properly.(especially vocab size , sched param and batch size)
After that, you might reach higher acc than now.
I hope this helps you.

**Comment by theblackcat102** [comment]
@jafioti If your dataset is very small (< 10 hours ), this model will not work ( or at least you need other tricks ). However if your target language is english, you can try to train a language model (checkout train_lm.py ) on your target datasets and dot product the predicted output results from your language model with the decoded outputs from RNN-T.
