### ISSUE TITLE
Could you please update the README.md to include a tutorial on using microphone for online data?

### ISSUE THREAD

**Issue by gevorgyana** [theblackcat102/edgedict#30]
As far as I understood, the project works with youtube videos, it would be also good to have a small recipe for using a microphone for real-time transcription. At least microphone data is the first thing that comes up to my mind when I think of 'streaming/online' ASR. Thank you!

**Comment by Rajratnpranesh** [comment]
Hi,
Were you able to find a way of streaming the audio through the microphone?

**Comment by theblackcat102** [comment]
FYI one of my branch have this function written, I remember testing last time its somewhat working ( before I got a properly trained model )

https://github.com/theblackcat102/edgedict/blob/zhirui/stream.py

Just commented out the code in the main part and you should start streaming audio from your mic
