### ISSUE TITLE
Online decoding for microphone input

### ISSUE THREAD

**Issue by Rajratnpranesh** [theblackcat102/edgedict#32]
Hi,

Great work! I was wondering if there is a way to stream microphone input and have the live decoding over it?
Adding such functionality will be very helpful. 

Best

**Comment by Rajratnpranesh** [comment]
I implemented it by myself :)

**Comment by gevorgyana** [comment]
Could you share? @Rajratnpranesh

**Comment by theblackcat102** [comment]
@gevorgyana @Rajratnpranesh  The implementation was available [here](https://github.com/theblackcat102/edgedict/blob/master/stream.py#L127)
